# Generated by Django 2.2 on 2020-02-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.CharField(default='pew pew pew', max_length=45),
            preserve_default=False,
        ),
    ]
